version: "3.7"

networks:
  cspro-testnet: {}

services:
  postgres:
    container_name: cstest-postgres
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    networks:
      - cspro-testnet
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    container_name: cstest-adminer
    image: adminer
    networks:
      - cspro-testnet
    ports:
      - "8080:8080"
  migration-service:
    container_name: cspro-migration-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - cspro-testnet
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    links:
      - postgres